### ISSUE TITLE
Ignore .DS_Store

### ISSUE THREAD

**Issue by leonma333** [zuoweifu/AvoidIt#1]
Remove `.DS_Store`, and put it in `.gitignore`.

**Comment by zuoweifu** [comment]
Removed .DS_Store

**Comment by leonma333** [comment]
@zuoweifu `.DS_Store` has not completely removed yet, there is one in your `Avoidlt` dir. And there will always be auto generated by the OS in your local, for your connivence and code cleanness pls put the following in the `.gitignore` in project root dir:

```
*.DS_Store
```
